# Resource related properties

TRAIN_DATASET = "train.csv"
TEST_DATASET = "test.csv"

RESOURCES_PATH = "./resources/"

INPUT_PATH = RESOURCES_PATH + "input/"
OUTPUT_PATH = RESOURCES_PATH + "output/"

PICTURE_PATH = OUTPUT_PATH + "pics/"
SUBMISSION_PATH = OUTPUT_PATH + "submission/"

FORMAT_PNG = ".png"
FORMAT_CSV = ".csv"

TRAIN_PATH = INPUT_PATH + TRAIN_DATASET
TEST_PATH = INPUT_PATH + TEST_DATASET
